debug: True
host: "127.0.0.1"
port: 5000
app_secret_key: "update_me"
sqlalchemy_track_modifications: False
sqlalchemy_database_uri: "sqlite:///users.db"
log_file: "loginapp.log"
log_level: "NOTSET"

captcha_public_key: "<public_key>"
captcha_private_key: "<private_key>"
hidden_address: "email@example.com"